name: "Setup All Environments"
description: |
    "Set up all the environments for python projects."
    "Cache the pipenv virtual environments"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [[ "${OSTYPE}" =~ "linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libsystemd-dev
        fi
    - uses: 'actions/setup-node@v3'
      with:
        node-version: '14'
    - shell: bash
      run: |
        npm install --global shx@0.3.3
    - uses: 'actions/setup-python@v4'
      id: python38
      with:
        python-version: '3.8'
        cache: "pipenv"
        cache-dependency-path: |
          **/setup.*
          **/Pipfile.*
          .github/actions/python/setup-all-environments/action.yaml
    - shell: bash
      name: install pipenv on 3.8
      run: python pip install pipenv==2021.5.29
    - shell: bash
      if: steps.python38.outputs.cache-hit == 'false'
      working-directory: environments
      name: setup ot3
      run: make -C ot-3 setup
    - uses: 'actions/setup-python@v4'
      id: python310
      with:
        python-version: '3.10'
        cache: "pipenv"
        cache-dependency-path: |
          **/setup.*
          **/Pipfile.*
          .github/actions/python/setup-all-environments/action.yaml
    - shell: bash
      name: install pipenv on 3.10
      run: python -m pip install pipenv==2021.5.29
    - shell: bash
      if: steps.python310.outputs.cache-hit == 'false'
      working-directory: environments
      name: setup the environments
      run: | # is this actually faster ??? ~15min for the non-parallel
        make -C ot-2 setup & \
        make -C dev setup & \
        make -C app setup & \
        wait;
