name: "Setup All Environments"
description: |
    "Set up all the environments for python projects."
    "Cache pip global cache directory to help speed up pipenv sync."

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [[ "${OSTYPE}" =~ "linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libsystemd-dev
        fi
    - uses: 'actions/setup-node@v3'
      with:
        node-version: '14'
    - shell: bash
      run: |
        npm install --global shx@0.3.3
    - uses: 'actions/setup-python@v4'
      id: python38
      with:
        python-version: '3.8'
        cache: "pipenv"
        cache-dependency-path: |
          **/setup.*
          **/Pipfile.*
    - shell: bash
      name: install pipenv on 3.8
      run: make install-pipenv
    - shell: bash
      working-directory: environments
      name: setup ot3
      run: make -C ot-3 setup
    - uses: 'actions/setup-python@v4'
      id: python310
      with:
        python-version: '3.10'
        cache: "pipenv"
        cache-dependency-path: |
          **/setup.*
          **/Pipfile.*
    - shell: bash
      name: install pipenv on 3.10
      run: make install-pipenv
    - shell: bash
      name: setup the environments
      run: make setup-py PYTHON_SETUP_DIRS="environments/ot-2 environments/dev environments/app" -j
