name: 'Setup a single Python environment'
description: |
  "Set up an environment with a specific Python."
  "Cache pipenv virtual environments but still always run make setup which runs pipenv sync."
inputs:
  python-version:
    description: 'Which Python version?'
    required: true
  environment:
    description: 'Which environment?'
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        if [[ "${OSTYPE}" =~ "linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libsystemd-dev
        fi
    - uses: 'actions/setup-node@v3'
      with:
        node-version: '14'
    - shell: bash
      run: npm install --global shx@0.3.3
    - uses: 'actions/setup-python@v4'
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pipenv'
        cache-dependency-path: |
          **/setup.*
          **/Pipfile.*
    - name: Install pipenv
      shell: bash
      run: make install-pipenv
    - shell: bash
      working-directory: environments
      name: setup ${{ inputs.environment }}
      run: make -C ${{ inputs.environment }} setup
