name: 'Python Setup'
description: 'Set up the environment to handle a monorepo python project'
inputs:
  project:
    description: 'Which project (by subdirectory) to set up'
    required: true
  target:
    description: 'Which makefile operation to preform'
    required: false
    default: 'setup'
runs:
  using: 'docker'
  image: 'docker://otsam/otbuildy:0.0.1'
  args: 
  - 'git clone https://github.com/Opentrons/opentrons.git && cd opentrons && git checkout ${{GITHUB_SHA}} && make -C ${{ inputs.project}} ${{inputs.target}}'
