name: 'Python Setup'
description: 'Set up the environment to handle a monorepo python project'
inputs:
  project:
    description: 'Which project (by subdirectory) to set up'
    required: true # now only viable for g-code-testing and hardware-testing
  python-version:
    description: "The version of Python to map to 'python' on path. Also sets OT_PYTHON with the full path to this version"
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        if [[ "${OSTYPE}" =~ "linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libsystemd-dev
        fi
    - uses: 'actions/setup-node@v3'
      with:
        node-version: '14'
    - shell: bash
      run: |
        npm install --global shx@0.3.3
    - uses: 'actions/setup-python@v4'
      with:
        python-version: ${{ inputs.python-version }}
    - name: Set the OT_PYTHON env variable
      shell: bash
      run: echo "OT_PYTHON=$(which python)" >> $GITHUB_ENV
    - name: install pipenv==2021.5.29
      shell: bash
      run: $OT_PYTHON -m pip install pipenv==2021.5.29
    - shell: bash
      name: setup project ${{ inputs.project }}
      run: 'make -C ${{ inputs.project }} setup'
