name: 'Python Setup'
description: |
  "Set up the environment to handle a monorepo python project"
  "Cache pipenv virtual environments but still always run make setup which runs pipenv sync."
inputs:
  project:
    description: 'Which project (by subdirectory) to set up?'
    required: true # now only viable for g-code-testing, hardware-testing, usb-bridge
  python-version:
    description: "The version of Python to map to 'python' on path."
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        if [[ "${OSTYPE}" =~ "linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libsystemd-dev
        fi
    - uses: 'actions/setup-node@v3'
      with:
        node-version: '16'
        cache: 'yarn'
    - shell: bash
      run: make setup-js-root
    - uses: 'actions/setup-python@v4'
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pipenv'
        cache-dependency-path: |
          **/setup.*
          **/Pipfile.*
    - name: install pipenv
      shell: bash
      run: make python-globals
    - shell: bash
      name: setup project ${{ inputs.project }}
      run: make -C ${{ inputs.project }} setup
