name: 'Python Setup'
description: 'Set up the environment to handle a monorepo python project'
inputs:
  project:
    description: 'Which project (by subdirectory) to set up'
    required: true
  python-version:
    description: "What Python version to use to create the project's virtual environment"
    required: false
  make-setup-recipe:
    description: "For overriding the default `make setup` command with a custom setup recipe"
    required: false
    default: "setup"
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        if [[ "${OSTYPE}" =~ "linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libsystemd-dev
        fi
    - shell: bash
      run: |
        npm install --global shx@0.3.3
        pip install pipenv==2021.5.29
    - shell: bash
      run: 'make -C ${{ inputs.project }} ${{ inputs.make-setup-recipe }} OT_VIRTUALENV_VERSION=${{ inputs.python-version }}'