# This workflow runs test and lint on branch pushes that touch the
# robot-server project or its dependencies

name: 'Robot server lint/test'

on:
  # Most of the time, we run on pull requests, which lets us handle external PRs
  push:
    paths:
      - 'api/**/*'
      - 'hardware/**/*'
      - 'Makefile'
      - 'shared-data/**/*'
      - '!shared-data/js/**/*'
      - 'robot-server/**/*'
      - 'notify-server/**/*'
      - 'scripts/**/*.mk'
      - 'scripts/**/*.py'
      - '.github/workflows/robot-server-test-lint.yaml'
      - '.github/actions/python/**'
    branches:
      - 'edge'
      - 'release'
      - '*hotfix*'
    tags-ignore:
      - '*'
  pull_request:
    paths:
      - 'api/**/*'
      - 'hardware/**/*'
      - 'Makefile'
      - 'shared-data/**/*'
      - '!shared-data/js/**/*'
      - 'robot-server/**/*'
      - 'notify-server/**/*'
      - 'scripts/**/*.mk'
      - 'scripts/**/*.py'
      - '.github/workflows/robot-server-test-lint.yaml'
      - '.github/actions/python/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ matrix.with-ot-hardware }}-${{ github.event.pull_request.number || github.ref }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint-test:
    name: 'robot server package linting and tests'
    timeout-minutes: 35
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: './.github/actions/python/setup-all-environments'
        id: "setup"
      - name: black-check
        if: always() && steps.setup.outcome == 'success'
        run: make -C api black-check
      - name: flake8
        if: always() && steps.setup.outcome == 'success'
        run: make -C api Flake8
      - name: mypy-ot2
        if: always() && steps.setup.outcome == 'success'
        run: make -C api mypy-ot2
      - name: mypy-ot3
        if: always() && steps.setup.outcome == 'success'
        run: make -C api mypy-ot3
      - name: Test
        run: make -C robot-server test-cov
      - name: Ensure assets build
        run: make -C robot-server sdist wheel
      - name: Upload coverage report
        uses: 'codecov/codecov-action@v3'
        with:
          files: ./robot-server/coverage.xml
          flags: robot-server
