name: 'Start OT-3 build'
on:
  push:
    branches:
      - edge
      - chore_bump-*
      - chore_release-*
      - release*
    tags:
      - ot3@*
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

jobs:
  handle-release:
    runs-on: 'ubuntu-latest'
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    name: "Start an OT-3 release build for tag ${{ github.ref }}."
    steps:
      - name: 'start build'
        uses: octokit/request-action@v2.x
        env:
            GITHUB_TOKEN: ${{ secrets.OT3_BUILD_CROSSREPO_ACCESS }}
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow-id}/dispatches
          owner: opentrons
          repo: oe-core
          workflow-id: build-ot3-actions.yml
          ref: RCORE-468_add_releases_json
          inputs: |
            {
              "oe-core-ref": "-",
              "monorepo-ref": "${{ github.ref }}",
              "infra-stage": "stage-prod",
              "build-type": "develop"
            }


