# This workflow runs tests and lint on non-release branches pushed that alter
# the update-server subpackage

name: 'Update Server test/lint'

on:
  push:
    paths:
      - 'update-server/**/*'
      - 'Makefile'
      - 'scripts/**/*.mk'
      - 'scripts/**/*.py'
      - '.github/workflows/update-server-lint-test.yaml'
      - '.github/actions/python/**'
    branches: # ignore any release-related thing (handled elsewhere)
      - 'edge'
    tags-ignore:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'update-server/**/*'
      - 'Makefile'
      - 'scripts/**/*.mk'
      - 'scripts/**/*.py'
      - '.github/workflows/update-server-lint-test.yaml'
      - '.github/actions/python/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint-test:
    name: 'update server linting and testing'
    timeout-minutes: 20
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: './.github/actions/python/setup-all-environments'
      - name: Lint
        run: make -C update-server lint
      - name: Test
        run: make -C update-server test
      - uses: 'codecov/codecov-action@v3'
        with:
          files: ./update-server/coverage.xml
          flags: update-server
